version: "3.8"
services:
  mongo:
    image: mongo:4.4.6
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mydockernet
    volumes:
      - app_mongo:/data/db
networks:
  mydockernet:
    driver: bridge
volumes:
  app_mongo: